name: CI Pipeline

on:
  push:
    branches:
      - main  # Change this to your default branch if different

jobs:
  validate:
    runs-on: windows-latest  # Use a Windows runner for PowerShell scripts

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up PowerShell
        uses: actions/setup-powershell@v2

      - name: Validate PowerShell Scripts
        run: |
          pwsh -File test-scripts.ps1
